### PR TITLE
Resizable editor!

### PR DESCRIPTION
**Pull request by kpsuperplane**
Saves to settings.

screen shot 2017-03-12 at 3 18 32 am

### CODE REVIEW

**Comment by YLiLarry** [comment]
Can we merge this?

**Comment by YLiLarry** [comment]
It may be good if we show instructors this before the next course meeting, allowing some time for feedback.

**Comment by kpsuperplane** [comment]
@e45lee what do you think? I'll resolve the merge conflicts in the meanwhile

**Comment by Happytofu** [comment]
This is gonna cause so many conflicts down the line (like it already has, unless we stop work on the UI), and I'd like to be able to show it to the instructors soon, so can we get this merged fast quick hayaku.

**Comment by kpsuperplane** [comment]
Changes have been merged

**Comment by Happytofu** [comment]
@e45lee if no one objects I'm merging this...

**Pull request merged**
