### PR TITLE
[frontend] Added "commit" button according to issue #142.

### PR DESCRIPTION
**Pull request by kcolford**
The dialog button is also bound to the key control+S to conform to the
style of the other buttons.  It was placed to the right of the TEST
button because like the TEST and RUN buttons it affects the project as
a whole (not just a specific file).

### CODE REVIEW

**Comment by e45lee** [comment]
Unfortuantely, we can't merge your pull-request as is; we are currently refactoring the Seashell frontend code, so your PR won't work right now.

In particular, we're using Angular these days.  There's a few examples of how modals are set up in
the Seashell code w/ Angular (see src/frontend/frontend/frontend.js).  If you could rewrite the dialog
handling code that you currently have (in src/frontend/js/setup.js and src/frontend/js/ui/menu.js),
then I can go ahead and try to merge this PR.

**Comment by kcolford** [comment]
Angular has been incorperated, I don't know how you are binding UI events to API calls, so that will have to be done by someone else or someone will have to point out where this is being done already.

I left the old non-Angular code in because it can still be backported to the old stable release.

**Comment by e45lee** [comment]
A good example of how UI events (and data) are being bound to API calls can be found at https://github.com/cs136/seashell/blob/master/src/frontend/frontend/frontend.js#L66-L89, with the template found
https://github.com/cs136/seashell/blob/master/src/frontend/frontend/templates/new-file-template.html.

I would prefer if you would set up the commit dialog modal the same way (i.e not in the project service, and without jQuery to fetch input contents).

FYI, we're probably not backporting anything to the old release (but it's fine to leave what you have there).

**Comment by kcolford** [comment]
Alright, this one is exactly as you asked for (commit dialog model in frontend.js and no jQuery).  All the UI events are hooked up except the keyboard events, that might come in a later patch.

**Comment by e45lee** [comment]
Looks fine to me.

**Pull request merged**
