### PR TITLE
Enlarge editor

### PR DESCRIPTION
**Pull request by YLiLarry**
request #648 

* Shrink the padding of the entire webpage from 5em to 30px
* Remove margin around the editor when the screen is smaller than 1440px in width
* Clear up the editor size calculation code, remove window-resized event which is only used by this piece of code. Use css instead.
* Editor is now 66% window height in vertical split mode, 70% window height in horizontal split mode

### CODE REVIEW

**Comment by kpalway** [comment]
I would prefer not to merge a change like this until after the frontend rewrite. Unless we have tested it in all supported browsers with different resolutions including the classroom projectors, and have some consensus among instructors that this is the interface they want.

**Comment by YLiLarry** [comment]
Reverted resizing code. I'm going to make a separate PR for resizable UI.
You need to merge this to fix issue #648

**Comment by kpalway** [comment]
Didn't the revert from earlier this week fix that issue? That was why we reverted it.

**Comment by YLiLarry** [comment]
Olga Dan and I had further discussion about this after the meeting. I think this is what Dan wants.

**Comment by kpalway** [comment]
Okay, has it been tested it on the different browsers and on the projector?

**Comment by YLiLarry** [comment]
I want to have this on staging for instructor feedback.

**Comment by kpalway** [comment]
Okay, make sure we test it thoroughly before our next release, I want to cut down on back and forth UI changes we've been having so far this term.

**Comment by YLiLarry** [comment]
Sounds good! :D

**Pull request merged**
