### PR TITLE
80 char alert

### PR DESCRIPTION
**Pull request by YLiLarry**
Everyone happy with this color?

qq20160203-0
qq20160203-1

### CODE REVIEW

**Comment by Gibstick** [comment]
There are performance issues with this once you get past a small number of lines. They might have huge test files, and we don't want to break those. Also, on slower computers typing becomes janky. Can you look into doing this by only looking at the current line and dealing with paste events?

**Comment by YLiLarry** [comment]
How about a periodical check per 5 seconds?

**Comment by Gibstick** [comment]
I don't think five seconds will help. It will just be a pause every five
seconds.

If it's too difficult to do what I suggested above, then go for only
highlighting the current line.

**Comment by YLiLarry** [comment]
Wait I thought you meant only highlight the current line. 
You meant only check 80 chars in the current line while keeping other highlighted lines unchanged, unless there's a paste event? Sure that's not hard.

**Comment by Gibstick** [comment]
Yes, that's what I mean. Only check what you have to. And I guess you have
to check the entire file when it is first loaded.

**Comment by YLiLarry** [comment]
Good advice. I'm on it.

**Pull request merged**
