### PR TITLE
Fix Issue #404: Control+U is bound to undo as well as test

### PR DESCRIPTION
**Pull request by YLiLarry**
Issue #404
Rebound test hotkey to Control+E

### CODE REVIEW

**Comment by Gibstick** [comment]
Ctrl+Shift+R is already bound to regex search in CodeMirror

**Comment by YLiLarry** [comment]
Are you sure? I tried that combo on my mac and nothing happened, so I chose it. 
Anyways, any idea what could be a good combo?

**Comment by e45lee** [comment]
That might be AppleKey-Shift-R on the Mac.  Try Ctrl-E (evaluate), if that's not already bound?

**Comment by e45lee** [comment]
One quick note: we land merges in master.  Please have your PR target that branch, thanks.

**Comment by Gibstick** [comment]
Don't worry too much about this, Larry. Bryan gets confused about the
branches every week.

**Pull request closed without merging**
