### PR TITLE
put runtime-files in temporary folder when using using seashell-cli

### PR DESCRIPTION
**Pull request by yc2lee**

### CODE REVIEW

**Comment by e45lee** [comment]
Don't we want the runtime-files directory in /tmp in the CLI tool?

**Comment by Gibstick** [comment]
@e45lee I thought this was preferable, so I told him to do it this way. But /tmp is fine too.

**Comment by e45lee** [comment]
I have a slight preference to /tmp here, as avoiding frequent network writes is preferable (~cs136t is mounted over NFS).  It would be nice if this was configurable, see #437.

**Comment by e45lee** [comment]
Looks good, I'll merge and fix the spelling mistake, thanks.

**Pull request merged**
